apiVersion: v1
kind: ConfigMap
metadata:
  name: maintenance-page
data:
  maintenance.html: |-
    <!--HTML GOES HERE-->
    <!doctype html>
    <title>Site Maintenance</title>
    <link rel="stylesheet" href="maintenance.css">
    <article>
        <h1>We&rsquo;ll be back soon!</h1>
        <div>
            <p>Sorry for the inconvenience but we&rsquo;re performing some maintenance at the moment. If you need to you can always <a href="mailto:#">contact us</a>, otherwise we&rsquo;ll be back online shortly!</p>
            <p>&mdash; The Team</p>
        </div>
    </article>
  maintenance.css: |-
    /* CSS GOES HERE */
    body { text-align: center; padding: 150px; background-color: #D3D3D3;}
    h1 { font-size: 50px; }
    body { font: 20px Helvetica, sans-serif; color: #333; }
    article { display: block; text-align: left; width: 650px; margin: 0 auto; }
    a { color: #dc8100; text-decoration: none; }
    a:hover { color: #333; text-decoration: none; }
    img { border-radius: 50%; }
  default.conf: |-
    # NGINX CONFIGURATION GOES HERE
    server { 
      listen 80 default_server;
      server_name  _ ;

      location / {
        if (-f /usr/share/nginx/html/maintenance/maintenance.html) {
          return 503;
        }
      }
      
      # for all routes, return maintenance page
      error_page 503 @maintenance;
      location @maintenance {
        root    /usr/share/nginx/html/maintenance/;
        rewrite ^(.*)$ /maintenance.html break;
      }

      # allow images and css to be retrieved
      location ~* \.(png|jpg|jpeg|css) {
        root /usr/share/nginx/html/maintenance/;
      }
    }
