apiVersion: v1
kind: Service
metadata:
  name: maintenance-page
spec:
  type: NodePort
  selector:
    app: maintenance-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
